/**
 * Nigeria's major cultures — seed data for cultural grounding.
 * Each entry provides the LLM with authentic cultural context.
 *
 * NOTE: This is v1 seed data. A Yoruba, Igbo, Idoma, Tiv, etc.
 * cultural advisor should review each entry. Corrections are one-line edits.
 */

export const CULTURES = {
  yoruba: {
    name: 'Yoruba',
    autonym: 'Yorùbá',
    region: 'South-West Nigeria (Lagos, Ogun, Oyo, Osun, Ondo, Ekiti, Kwara)',
    greeting: { hi: 'Ẹ n lẹ', response: 'Ẹ n lẹ o' },
    keyValues: ['respect for elders', 'ẹ̀kọ́ (education)', 'oríkì (praise poetry)'],
    kingTitle: 'Ọba',
    famousKing: 'The Ọọ̀ni of Ifẹ̀',
    landmark: 'Ilé-Ifẹ̀ — the birthplace of Yoruba civilisation',
    trickster: 'Ìjàpá (the tortoise)',
    proverb: { text: 'Ilé làbọ̀ sinmi oko', meaning: 'The home is where we rest after the journey of the farm.', lang: 'Yoruba' },
    colors: ['indigo', 'gold', 'earth-brown'],
    fabric: 'Aso-oke, Adire, Ankara',
    drum: 'Talking drum (Gángan)',
    language: 'yoruba',
  },
  igbo: {
    name: 'Igbo',
    autonym: 'Ndi Igbo',
    region: 'South-East Nigeria (Anambra, Enugu, Imo, Abia, Ebonyi)',
    greeting: { hi: 'Kedu', response: 'Ọ dị mma' },
    keyValues: ['ìgbo (community)', 'ọ̀fọ̀ (justice)', 'nzụkọ (gathering)'],
    kingTitle: 'Igwe / Eze',
    famousKing: 'The Eze of Nri — the ancient spiritual king',
    landmark: 'The Niger Bridge at Onitsha; the Ogbunike Caves',
    trickster: 'Mbe (the tortoise)',
    proverb: { text: 'Igbo kwenu', meaning: 'The strength of the community is the strength of each person.', lang: 'Igbo' },
    colors: ['red', 'black', 'white', 'green'],
    fabric: 'George, Akwete, Isiagu',
    drum: 'Igba, Ogene, Ikoro',
    language: 'igbo',
  },
  hausa: {
    name: 'Hausa',
    autonym: 'Hausawa',
    region: 'North-West Nigeria (Kano, Katsina, Sokoto, Kaduna, Jigawa, Kebbi, Zamfara)',
    greeting: { hi: 'Sannu', response: 'Yauwa' },
    keyValues: ['addini (faith)', 'girmamawa (respect)', 'hausa (language)'],
    kingTitle: 'Sarki',
    famousKing: 'The Emir of Kano',
    landmark: 'The ancient walls of Kano — 14 kilometres of earthwork',
    trickster: 'Gizo (the spider)',
    proverb: { text: 'Komai nisan jifa, kasa zai dawo', meaning: 'However far a stone is thrown, it falls to the ground.', lang: 'Hausa' },
    colors: ['green', 'white', 'indigo'],
    fabric: 'Atamfa, Babban Riga, Kaftan',
    drum: 'Kalangu (talking drum)',
    language: 'hausa',
  },
  fulani: {
    name: 'Fulani',
    autonym: 'Fulɓe',
    region: 'Across the Sahel — especially Adamawa, Taraba, Bauchi, Gombe, Sokoto',
    greeting: { hi: 'Jam waali', response: 'Jam tan' },
    keyValues: ['pulaaku (dignity)', 'munyal (patience)', 'semteende (modesty)'],
    kingTitle: 'Lamido',
    famousKing: 'The Lamido of Adamawa',
    landmark: 'The Adamawa highlands; the Sahel savanna',
    trickster: 'The clever herder',
    proverb: { text: 'Man yetti, tana gani', meaning: 'Patience eats whatever is set before it.', lang: 'Fulfulde' },
    colors: ['white', 'orange', 'red'],
    fabric: 'White boubou, embroidered haird',
    drum: 'Hoddu, Fula drums',
    language: 'fulfulde',
  },
  idoma: {
    name: 'Idoma',
    autonym: 'Idoma',
    region: 'Benue State (Otukpo, Ogbadibo, Okpokwu, Obi, Ohimini)',
    greeting: { hi: 'Abole', response: 'Awo' },
    keyValues: ['unity', 'respect for the Alekwu (ancestors)', 'hard work'],
    kingTitle: 'Och\'Idoma',
    famousKing: 'The Och\'Idoma — paramount ruler in Otukpo',
    landmark: 'The Otukpo hills; the Benue river valley',
    trickster: 'Ijapa (shared with Yoruba via trade)',
    proverb: { text: 'Onye wu owo, o wu inya', meaning: 'The hand that gives is the hand that is blessed.', lang: 'Idoma' },
    colors: ['red', 'white', 'black'],
    fabric: 'Ukpo cloth, Aji',
    drum: 'Ogene, Ikpese',
    language: 'idoma',
  },
  tiv: {
    name: 'Tiv',
    autonym: 'Tiv',
    region: 'Benue State, parts of Taraba, Nasarawa, Plateau',
    greeting: { hi: 'M sugh u', response: 'M sugh u ga' },
    keyValues: ['kwagh-hir (storytelling)', 'swem (leadership)', 'ya (family)'],
    kingTitle: 'Tor Tiv',
    famousKing: 'The Tor Tiv',
    landmark: 'The Tiv highlands; the Kwagh-hir storytelling tradition',
    trickster: 'Hare (the clever hare in Tiv tales)',
    proverb: { text: 'Kwagh-hir kera a mngeren', meaning: 'The story is the eye of the child.', lang: 'Tiv' },
    colors: ['green', 'yellow', 'brown'],
    fabric: 'Anger cloth, A\'nger',
    drum: 'Kakaki, drums',
    language: 'tiv',
  },
  efik: {
    name: 'Efik',
    autonym: 'Efik',
    region: 'Cross River State (Calabar, Akpabuyo, Bakassi)',
    greeting: { hi: 'Mesiere', response: 'Mesiere' },
    keyValues: ['hospitality', 'ìwàdì (grace)', 'ukpe (sea-trade heritage)'],
    kingTitle: 'Obong of Calabar',
    famousKing: 'The Obong of Calabar',
    landmark: 'Calabar — the first capital of Nigeria; the Duke Town',
    trickster: 'The wise tortoise of Calabar tales',
    proverb: { text: 'Enyen emana edi', meaning: 'The visitor is like a king.', lang: 'Efik' },
    colors: ['red', 'gold', 'white'],
    fabric: 'Ukara cloth, Onyonyo',
    drum: 'Ekomo, Ekpo drums',
    language: 'efik',
  },
  ibibio: {
    name: 'Ibibio',
    autonym: 'Ibibio',
    region: 'Akwa Ibom State (Uyo, Eket, Ikot Ekpene, Oron)',
    greeting: { hi: 'Mesiere', response: 'Mesiere' },
    keyValues: ['family', 'Ekpo masquerade tradition', 'ibibio ékpè society'],
    kingTitle: 'Oku Ibom Ibibio',
    famousKing: 'The Oku Ibom Ibibio',
    landmark: 'The Ibibio Museum; Ikot Ekpene — "the Raffia City"',
    trickster: 'The clever tortoise of Ibibio tales',
    proverb: { text: 'Ekemede ọyọ ke ekemede', meaning: 'What brings joy is what brings peace.', lang: 'Ibibio' },
    colors: ['green', 'red', 'white'],
    fabric: 'Raffia, Akwa-Ocha',
    drum: 'Ikon, Nkuwa',
    language: 'ibibio',
  },
  ijaw: {
    name: 'Ijaw',
    autonym: 'Izon',
    region: 'Bayelsa, Rivers, Delta, Akwa Ibom (Niger Delta)',
    greeting: { hi: 'Bara tutu', response: 'Bara tutu' },
    keyValues: ['bravery on the water', 'family lineage', 'water spirit reverence'],
    kingTitle: 'Amanyanabo',
    famousKing: 'The Amanyanabo of Twon-Brass',
    landmark: 'The creeks of the Niger Delta; the Oloibiri oil well',
    trickster: 'The water spirit of Ijaw lore',
    proverb: { text: 'Ogu ịwụ mịnị, ogu mịnị', meaning: 'The water is the source of all things.', lang: 'Izon' },
    colors: ['blue', 'green', 'white'],
    fabric: 'Ijaw George, wrapper cloths',
    drum: 'Water drums, Ikpinya',
    language: 'izon',
  },
  edo: {
    name: 'Edo (Bini)',
    autonym: 'Edo',
    region: 'Edo State (Benin City, Ubiaja, Auchi)',
    greeting: { hi: 'Koyọ', response: 'Ọyẹn' },
    keyValues: ['ìwẹ̀ (beauty)', 'ure (lineage)', 'respect for the Oba'],
    kingTitle: 'Oba',
    famousKing: 'The Oba of Benin',
    landmark: 'The Benin City Walls — once the largest earthwork in the world; the Benin Bronzes',
    trickster: 'The clever tortoise of Benin tales',
    proverb: { text: 'Ọmọ ọba ọ ma gbọn ẹ̀fẹ̀', meaning: 'The child of the king does not lose their way home.', lang: 'Edo' },
    colors: ['red', 'coral', 'white'],
    fabric: 'Coral beads, Akwete cloth',
    drum: 'Ivbie, Ema drums',
    language: 'edo',
  },
  igala: {
    name: 'Igala',
    autonym: 'Igala',
    region: 'Kogi State (Idah, Ankpa, Dekina, Ofu)',
    greeting: { hi: 'À gbọ́n', response: 'À gbọ́n' },
    keyValues: ['Attah (kingship)', 'ọ̀jọ̀ (community)', 'ẹ̀kọ́ (learning)'],
    kingTitle: 'Àtá Igala',
    famousKing: 'The Àtá Igala at Idah',
    landmark: 'The confluence of the Niger and Benue at Lokoja',
    trickster: 'The clever tortoise of Igala tales',
    proverb: { text: 'Ọ̀kà kì í jọ ẹ̀wà', meaning: 'A corn cob never resembles a bean pod.', lang: 'Igala' },
    colors: ['red', 'white', 'black'],
    fabric: 'Achala, Igala wrapper',
    drum: 'Ọ̀pì, Igala drums',
    language: 'igala',
  },
  nupe: {
    name: 'Nupe',
    autonym: 'Nupe',
    region: 'Niger State (Bida, Mokwa, Lapai, Agaie)',
    greeting: { hi: 'Sokò', response: 'Kó' },
    keyValues: ['craftsmanship', 'Etsu (kingship)', 'Bida glass and brass heritage'],
    kingTitle: 'Etsu Nupe',
    famousKing: 'The Etsu Nupe at Bida',
    landmark: 'Bida — the centre of Nupe brass and glass work',
    trickster: 'The clever hare of Nupe tales',
    proverb: { text: 'Zàkà ná gbà', meaning: 'The hunter is the one who knows the forest.', lang: 'Nupe' },
    colors: ['green', 'yellow', 'white'],
    fabric: 'Bida cloth, Nupe wrapper',
    drum: 'Bata, Nupe drums',
    language: 'nupe',
  },
  kanuri: {
    name: 'Kanuri',
    autonym: 'Kanuri',
    region: 'Borno, Yobe (the Lake Chad basin)',
    greeting: { hi: 'Ndaro', response: 'Ndaro' },
    keyValues: ['Kanem-Bornu history', 'Shehu (spiritual leader)', 'desert trade heritage'],
    kingTitle: 'Shehu of Borno',
    famousKing: 'The Shehu of Borno',
    landmark: 'The ancient Kanem-Bornu Empire; the shores of Lake Chad',
    trickster: 'The clever jackal of Kanuri tales',
    proverb: { text: 'Kǝla kǝla kamburo', meaning: 'Step by step reaches the journey.', lang: 'Kanuri' },
    colors: ['white', 'green', 'blue'],
    fabric: 'Kanuri boubou, embroidered gowns',
    drum: 'Kanuri drums, Kalangu',
    language: 'kanuri',
  },
  mixed: {
    name: 'Mixed heritage',
    autonym: 'Nigeria',
    region: 'Nigeria — many traditions together',
    greeting: { hi: 'Sannu · Kedu · Ẹ n lẹ', response: 'Welcome to all of Nigeria' },
    keyValues: ['unity in diversity', 'àjọ jẹ (shared feast)', 'learning all traditions'],
    kingTitle: 'The President and all the royal fathers',
    famousKing: 'The Council of Traditional Rulers',
    landmark: 'The whole of Nigeria — 250+ ethnic groups, 500+ languages',
    trickster: 'Ìjàpá, Mbe, Gizo — all of them',
    proverb: { text: 'One tree does not make a forest', meaning: 'Many cultures together make Nigeria strong.', lang: 'English (pan-Nigerian)' },
    colors: ['green', 'white'],
    fabric: 'Every Nigerian fabric',
    drum: 'All Nigerian drums',
    language: 'english',
  },
};

export function getCulture(key) {
  return CULTURES[String(key || '').toLowerCase()] || CULTURES.mixed;
}

export function allCultureKeys() {
  return Object.keys(CULTURES);
}

export const AGE_LEVELS = {
  explorer: { min: 4, max: 6, label: 'Explorer', description: 'Very simple words. Short sentences. Big feelings.' },
  discoverer: { min: 7, max: 9, label: 'Discoverer', description: 'Full sentences. Real facts. Gentle challenges.' },
  scholar: { min: 10, max: 12, label: 'Scholar', description: 'Richer vocabulary. Historical depth. More complex questions.' },
};

export function ageLevel(age) {
  const a = Number(age) || 7;
  if (a <= 6) return 'explorer';
  if (a <= 9) return 'discoverer';
  return 'scholar';
}
